spring:
  application:
    name: rabbitmq-spring

  rabbitmq:
    #virtual-host: /  不配置即为默认的/
    port: 5672
    username: guest
    password: guest
    host: localhost
    publisher-confirms: true # 是否启用发布者确认
    publisher-returns: true  #  是否启用发布者返回
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 1
        retry:
          enabled: true
#    connection-timeout: 5s # 链接超时时间
